### ISSUE TITLE
Limit kokoro parallel builds / GB

### ISSUE THREAD

**Issue by mkurc-ant** [SymbiFlow/f4pga-arch-defs#1244]
Currently kokoro uses 1 build / 4GB of RAM. This is not enough when there are many tests requiring the full 50t graph (genfasm consumes ~10GB). No too many concurrent tests are run which leads to the system killing some of them due to resource starvation.

**Comment by mkurc-ant** [comment]
https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1222

**Comment by umarcor** [comment]
CI was changed to GitHub Actions and custom runners, so I'm closing this.
