### ISSUE TITLE
Provide better usage output for the toolchain wrappers

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/f4pga-arch-defs#1985]
Some of the toolchain wrappers do not have a `usage` output, making it difficult to understand the required arguments to call the wrappers.

**Comment by umarcor** [comment]
I'm closing this because the toolchain wrappers were removed from this repository. They are now located in [chipsalliance/f4pga](https://github.com/chipsalliance/f4pga), along with an alternative Python implementation.
