### ISSUE TITLE
Set up readthedocs

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/f4pga-arch-defs#21]
We want to have readthedocs and stuff generating documentation automatically.

**Comment by umarcor** [comment]
This is done already: 

- https://github.com/SymbiFlow/f4pga-arch-defs/blob/main/.readthedocs.yml
- https://f4pga.readthedocs.io/projects/arch-defs/en/latest/
- https://readthedocs.org/projects/symbiflow-arch-defs/
